# Generated by Django 3.0.3 on 2020-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201216_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagline',
            field=models.TextField(default=''),
        ),
    ]
